### ISSUE TITLE
Monitoring random failing test

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#179] opened 2015-05-12 08:33 UTC
See https://travis-ci.org/dice-cyfronet/atmosphere/builds/62196520 for details

**Comment by Nuanda** [comment] 2015-05-12 08:52
I also spotted that after my recent introduction of callback fix on nonmanaged VMs. It is not impossible that the fix caused this random fail to manifest.

**Comment by tbartynski** [comment] 2015-05-12 09:48
I hope 19cacf6736bfd9432192685a801e378270a7213d commit fixes it. I think that setting properties in Atmosphere settings that were not cleaned was the cause of the problem. I'm closing the issue for now. Reopen the issue in case the problem persists.

**Closed by tbartynski** 2015-05-12 09:48 UTC
Labels: bug
